= Starter Kits List

We want to help you create your dapp as fast as possible. We are creating a suite of starter kits that adapt to different use cases and stacks to supercharge your development.

You can find below all the starter kits available. Some of them are developed by us, while others are developed by the community.

== First-Party

These are the official Starter Kits. They are developed by OpenZeppelin and they are going to be maintained by us.

* xref:starter.adoc[Starter]: the basic Starter Kit. The perfect way to start a dapp from scratch.
* xref:tutorial.adoc[Tutorial]: an interactive tutorial. Shows you how all the components fit together.
* xref:gsnkit.adoc[GSN]: the best way to get started with Gas Station Network.

== Third-Party

These are the Starter Kits created by other companies and members of the community.

* https://github.com/provable-things/provable-starter-kit[Provable]. Power your dapp with data from external applications via Provable.

== Create Your Own!

OpenZeppelin Starter Kits are designed to turbocharge not just the developer experience, but also the community experience as well. Custom Starter Kits can be developed by anyone and installed by anyone directly via the OpenZeppelin SDK command line.

This is perfect for companies and projects looking to build educational tools on top of a standard platform. Example code now becomes complete hackable demo’s that the community can get started with fast.

TIP: Have an idea for a Starter Kit? Want to integrate your protocol and/or technology into a new kit? Send us a message at contact@openzeppelin.com and we'll do our best to assist you.
