= Tutorial

OpenZeppelin provides Tutorial Starter Kit which is usefull both for learning smart contract development, and jumpstarting hackathon projects. 

## Requirements

Install OpenZeppelin SDK, Ganache, and Truffle.

``
npm install -g truffle@5.0.2 ganache-cli@6.3.0 @openzeppelin/cli@2.5.0
``

## Installation

Ensure you are in a new and empty directory, and run the `unpack` command with `tutorial` to unpack the tutorial starter project:

``
openzeppelin unpack tutorial
``

This will not only unpack a complete Starter Kit, it will be prepopulated with solidity contracts and a react front end with an interactive tutorial to follow allong. 

## Run

In a new terminal window, run your local blockchain:

``
ganache-cli --deterministic
``

In your original terminal window, at the top level of your folder, initialize the project and follow the prompts:

``
openzeppelin init
``

In a new terminal window, in the `client` directory, run the React app:

``
cd client
npm run start
``

Open a web browser and navigate to: ``http://localhost:3000``. Follow along the tutorial directly from the React App. 
