= Tutorial Starter Kit

OpenZeppelin provides Tutorial Starter Kit which is useful both for learning smart contract development, and jumpstarting hackathon projects.

https://github.com/OpenZeppelin/starter-kit-tutorial[View repository]

== Installation

Ensure you are in a new and empty directory, and run the `unpack` command with `tutorial` to unpack the tutorial starter project:

```console
$ openzeppelin unpack tutorial
```

== Why This Kit?

This Starter Kit will show you how all the components work under the hood. It will guide
you through an interactive tutorial so you can learn by changing the code and adding new components.

You will learn the following:

* How to *Fund your Metamask* account.
* How to connect to your Ethereum network: local, testnets and mainnet.
* How to retrieve your accounts and balance.
* How to *call smart contract functions* from the frontend.,
* How to create a responsive UI based on smart contract updates.
* How to add new functionality to your smart contracts via *upgrades*.
* How to leverage *smart contract hot reloading* to speed up your local development.
